version: '3.8'

services:
  proxy-server:
    build: ./proxy-server
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090

  proxy-client:
    build: ./ProxyClient
    ports:
      - "8080:8080"
    environment:
      - CLIENT_PORT=8080
    depends_on:
      - proxy-server
